### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by andriisytnyk** [andriisytnyk/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by ZameAlex** [comment]
<h1 class="name">Ryu Hoshi (リュウ Ryū)</h1>
<div class="job">The main protagonist of the Street Fighter series</div>
<ul class="contacts">
  <li>
    <a href="https://www.facebook.com/profile.php?id=100004808958030" rel="author" class="facebook">
      <span>Ryu Hoshi on facebook</span>
    </a>
  </li>
  <li>
    <a href="ryuwins@gmail.com" rel="author" class="gmail">
      <span>Ryu Hoshi's gmail</span>
    </a>
  </li>
  <li>
    <a href="https://twitter.com/denjinryu" rel="author" class="twitter">
      <span>Ryu Hoshiin twitter</span>
    </a>
  </li>
  <li>
    <a href="https://www.instagram.com/sworn_ryu/" rel="author" class="instagram">
      <span>Ryu Hoshi in instagram</span>
    </a>
  </li>
</ul>
